# The following environment variables are required.
# They should be set in a CircleCI context called "docker".
#
# DOCKER_USER
# DOCKER_PASS
# DOCKER_REPO   eg. orgname/imagetag

version: 2

jobs:
  test:
    docker:
      - image: alpine:latest

    working_directory: ~/project

    steps:
    - checkout
    - run: echo "Tests!"


  build_and_push:
    docker:
      - image: docker:latest

    working_directory: ~/project

    steps:
    - setup_remote_docker
    - checkout
    - run: echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
    - run: |
        docker build -t ${DOCKER_REPO}:${CIRCLE_BRANCH} .
        docker push ${DOCKER_REPO}:${CIRCLE_BRANCH}

        if [[ "$CIRCLE_TAG" ]]; then
          docker tag ${DOCKER_REPO}:${CIRCLE_BRANCH} ${DOCKER_REPO}:${CIRCLE_TAG}
          docker tag ${DOCKER_REPO}:${CIRCLE_BRANCH} ${DOCKER_REPO}:latest
          docker push ${DOCKER_REPO}:${CIRCLE_TAG}
          docker push ${DOCKER_REPO}:latest
        fi

workflows:
  version: 2
  build_push:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/

      - build_and_push:
          context: docker
          requires:
            - test          
          filters:
            tags:
              only: /.*/
